# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en
## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
# locales: [es, fr]
## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    ## Default:
    # - config/locales/%{locale}.yml
    ## More files:
    # - config/locales/**/*.%{locale}.yml

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    ## For example, write devise and simple form keys to their respective files:
    # - ['{devise, simple_form}.*', 'config/locales/\1.%{locale}.yml']
    ## Catch-all default:
    # - config/locales/%{locale}.yml

  # External locale data (e.g. gems).
  # This data is not considered unused and is never written to.
  external:
    ## Example (replace %#= with %=):
    # - "<%#= %x[bundle info vagrant --path].chomp %>/templates/locales/%{locale}.yml"

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: conservative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  paths:
    # API
    - '../api/app/controllers'
    - '../api/app/helpers'
    - '../api/app/models'
    - '../api/app/serializers'
    - '../api/app/services'
    - '../api/app/views'

    # Frontend
    - '../frontend/app/controllers'
    - '../frontend/app/helpers'
    - '../frontend/app/models'
    - '../frontend/app/views'

    # Backend
    - '../backend/app/controllers'
    - '../backend/app/helpers'
    - '../backend/app/models'
    - '../backend/app/views'

    # Core
    - '../core/app/controllers'
    - '../core/app/finders'
    - '../core/app/helpers'
    - '../core/app/mailers'
    - '../core/app/models'
    - '../core/app/pagnators'
    - '../core/app/presenters'
    - '../core/app/services'
    - '../core/app/sorters'
    - '../core/app/validators'
    - '../core/app/views'


  # ## Root directories for relative keys resolution.
  # relative_roots:
  #   - app/controllers
  #   - app/helpers
  #   - app/mailers
  #   - app/presenters
  #   - app/views

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  # strict: true

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Translation Services
translation:

## Do not consider these keys missing:
ignore_missing:
  - 'date.month_names'
  - 'date.abbr_day_names'
  - 'spree.date_picker.*'
  - 'spree.fpr_human_friendly_date_format'
  - 'spree.fpr_human_friendly_date_time_format'
  - 'views.pagination.truncate'
  - 'number.currency.format.separator'
  - 'activerecord.models.spree/address'

## Consider these keys used:
ignore_unused:
  - 'spree.date_picker.*'
  - 'spree.fpr_human_friendly_date_format'
  - 'spree.fpr_human_friendly_date_time_format'
  - 'spree.promotion_action_types.*'
  - 'spree.promotion_rule_types.*'
  - 'spree.shipment_states.*'
  - 'spree.state_machine_states.*'
  - 'spree.return_authorization_states.*'
  - 'spree.promotion_form.match_policies.*'
  - 'spree.product_rule.*'
  - 'spree.payment_states.*'
  - 'spree.order_state.*'
  - 'spree.item_total_rule.*'
  - 'spree.events.*'
  - 'spree.eligibility_errors.messages.*'
  - 'spree.admin.order.events.*'
  - 'spree.adjustment_labels.tax_rates.*'
  - 'spree.address_book.*'
  - 'spree.validation.*'
  - 'spree.taxon_rule.*'
  - 'spree.shipping_rates.*'
  - 'errors.messages.*'
  - 'devise.*'
  - 'activerecord.*'
  - 'activemodel.*'
  - 'number.*'
  - 'pagination.*'
  # not sure
  - 'spree.i18n.*'
  - 'spree.actions.*'

## Exclude these keys from the `i18n-tasks eq-base' report:
# ignore_eq_base:
#   all:
#     - common.ok
#   fr,es:
#     - common.brand

## Exclude these keys from the `i18n-tasks check-consistent-interpolations` report:
# ignore_inconsistent_interpolations:
# - 'activerecord.attributes.*'

## Ignore these keys completely:
# ignore:
#  - kaminari.*

## Sometimes, it isn't possible for i18n-tasks to match the key correctly,
## e.g. in case of a relative key defined in a helper method.
## In these cases you can use the built-in PatternMapper to map patterns to keys, e.g.:
#
# <%# I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper',
#       only: %w(*.html.haml *.html.slim),
#       patterns: [['= title\b', '.page_title']] %>
#
# The PatternMapper can also match key literals via a special %{key} interpolation, e.g.:
#
<% I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper', patterns: [['\bSpree\.t[( ]\s*%{key}', 'spree.%{key}']] %>
